### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ComputerCrash0** [blaz1988/keylogger#1]
When trying to run your script you will get then following error.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyHook\HookManager.py", line 351, in KeyboardSwitch
    return func(event)
  File "C:/Log_Test.py", line 13, in OnKeyboardEvent
    f=open('c:\output.txt','r+')
IOError: [Errno 2] No such file or directory: 'c:\\output.txt'

**Comment by adishjain** [comment]
You'll have to create the 'output.txt' file yourself. 
Also it will be helpful if you change the path to some location that doesn't require admin access to modify files' content.

**Comment by freeugali** [comment]
output.txt file?? 
Admin access to modify text??

**Comment by freeugali** [comment]
http://hackspc.com/keylogger.rar thefile u uploaded isnt found.. was removed.. mind resharing

**Comment by saiv123** [comment]
can anyone help me the code is not working and i made the output.txt
it is saying that there is a syntax error with the unicodeescape on line 13 col:15

**Comment by freeugali** [comment]
@saiv123 which code
